```{r}
setwd("R:/Users/rsimpao/repo=rstudio/pokemon_index_project")

# install packages from file
# packages <- readLines("packages.txt")
# install.packages(packages)

library(conflicted)
library(tidyverse)
library(ggplot2)
```

```{r}
pokedex = read_csv("data/processed/pokedex.csv", col_types = cols(.default = "c"))

pokedex = pokedex %>%
  mutate(across(starts_with("stat_"), as.numeric))

# pokedex2 = pokedex %>%
#   dplyr::filter(.$generation == "I" | .$generation == "II") %>% 
#   arrange(as.numeric(.$id),decreasing=FALSE)
# 
# write.csv(pokedex2, "data/processed/pokedex12.csv")

gen1 = pokedex %>% 
  dplyr::filter(.$generation == "I")

gen2 = pokedex %>% 
  dplyr::filter(.$generation == "II")

gen3 = pokedex %>% 
  dplyr::filter(.$generation == "III")

gen4 = pokedex %>% 
  dplyr::filter(.$generation == "IV")

gen5 = pokedex %>% 
  dplyr::filter(.$generation == "V")

gen6 = pokedex %>% 
  dplyr::filter(.$generation == "VI")

gen7 = pokedex %>% 
  dplyr::filter(.$generation == "VII")

gen8 = pokedex %>% 
  dplyr::filter(.$generation == "VIII")

gen9 = pokedex %>% 
  dplyr::filter(.$generation == "IX")

all_gens = list(gen1=gen1,
                gen2=gen2,
                gen3=gen3,
                gen4=gen4,
                gen5=gen5,
                gen6=gen6,
                gen7=gen7,
                gen8=gen8,
                gen9=gen9)
```

## Checking for Normality

* Shapiro-Wilk Test

* Histogram of variables

* Quantile-Quantile plot

```{r}
shapiro.test(gen1$stat_hp)
shapiro.test(gen1$stat_atk)
shapiro.test(gen1$stat_sp_atk)
shapiro.test(gen1$stat_def)
shapiro.test(gen1$stat_sp_def)
```

```{r}
create_plot = function(stat, plot_type="hist"){
  if(plot_type == "normal"){
    plot(dnorm(stat), main=plot_type)
  }else if(plot_type == "hist"){
    hist(stat)
  }else if(plot_type == "qq"){
    qqnorm(stat)
    qqline(stat)
  }else{
    plot(stat, main=plot_type)
  }
}

check_normality = function(stat, use_log=FALSE){
  if(use_log){
    stat = log(stat)
  }
  
  create_plot(stat, plot_type="qq")
  
  print(shapiro.test(stat))
}
```

```{r}
# comparing the hp distribution between all generations

for(gen in all_gens){
  check_normality(stat=gen$stat_hp, use_log=TRUE)
}
```


